# Generated by Django 4.0.10 on 2024-06-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('file_type', models.IntegerField(choices=[(0, 'Jpg'), (1, 'Avi')], default=None, null=True)),
                ('file_path', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='storageinfo',
            name='record_file_type',
            field=models.IntegerField(default=1),
        ),
    ]
