# Generated by Django 4.0.10 on 2024-06-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicevideoinfo',
            name='enabled_main',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='devicevideoinfo',
            name='enabled_sub',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='devicevideoinfo',
            name='enabled_third',
            field=models.BooleanField(default=True),
        ),
    ]
