# Generated by Django 4.0.10 on 2024-06-04 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0004_deviceimageinfo_exposure_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceimageinfo',
            name='night_mode_exposure_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deviceimageinfo',
            name='day_exposure_Gain',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='deviceimageinfo',
            name='day_exposure_time',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='deviceimageinfo',
            name='night_exposure_Gain',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
