# Generated by Django 4.0.10 on 2024-06-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0008_deviceimageinfo_wdr_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceOSDSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name_enabled', models.BooleanField(default=True)),
                ('camera_name', models.CharField(default='IP CAMERA', max_length=50)),
                ('background_color', models.IntegerField(choices=[(0, 'Transparent'), (1, 'White'), (2, 'Grey'), (3, 'Red'), (4, 'Green'), (5, 'Blue'), (6, 'Black'), (7, 'Transparent Red'), (8, 'Transparent Green'), (9, 'Transparent Blue')], default=2)),
                ('font_color', models.IntegerField(choices=[(0, 'Transparent'), (1, 'White'), (2, 'Grey'), (3, 'Red'), (4, 'Green'), (5, 'Blue'), (6, 'Black'), (7, 'Transparent Red'), (8, 'Transparent Green'), (9, 'Transparent Blue')], default=1)),
                ('datetime_enabled', models.BooleanField(default=True)),
                ('datetime_display_position', models.IntegerField(choices=[(0, 'Left Top'), (1, 'Center Top'), (2, 'Right Top'), (3, 'Left Bottom'), (4, 'Center Bottom'), (5, 'Right Bottom')], default=0)),
                ('intelligent_osd_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
