# Generated by Django 4.0.10 on 2024-06-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0009_deviceosdsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='osd_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='device_info.deviceosdsetting'),
            preserve_default=False,
        ),
    ]
