# Generated by Django 4.0.10 on 2024-06-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0010_deviceinfo_osd_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='osd_info',
        ),
    ]
