# Generated by Django 4.0.10 on 2024-06-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0015_alter_deviceinfo_basic_info_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceOSDSetting',
            new_name='DeviceOSDInfo',
        ),
    ]
